### ISSUE TITLE
Problem deserializing JSON object as a Dictionary

### ISSUE THREAD

**Issue by glenwong** [jacobdufault/fullserializer#15]
It seems fullserializer does not serialize JSON dictionaries? Running the code below I get the following RawMessage: fsIEnumerableConverter expected Array but got Object in {"someKey":"someValue"}

```c#
public class SomeObject {
  public Dictionary<string, string> someField;
}

fsData data = fsJsonParser.Parse("{\"someField\": {\"someKey\": \"someValue\"}}");
object deserialized = null;
var serializer = new fsSerializer ();
serializer.TryDeserialize(data, typeof(someObject), ref deserialized).AssertSuccessWithoutWarnings();
```

**Comment by jacobdufault** [comment]
The JSON dictionary in your example is available in the `fsData data` instance - the actual dictionary content is available as `data.AsDictionary`.

I'd recommend taking a look at the serializer output for some examples to see how the serialization data is encoded into JSON. Generally though, serializing dictionaries as JSON objects is a bad idea w.r.t. robustness because it requires that keys be serializable as strings, which is frequently not the case (for example, with `Dictionary<ComplexKey, ComplexValue>`).

For your example, the expected JSON data is the following:

```json
{
    "someField": [
        {
            "Key": {
                "$content": "someKey",
                "$type": "System.String"
            },
            "Value": {
                "$content": "someValue",
                "$type": "System.String"
            }
        }
    ]
}
```

The `$type` fields are there due to cross-platform compatibility issues w.r.t. generics.
