### ISSUE TITLE
fsResult.Fail in custom converters does not fail a de/serialization process

### ISSUE THREAD

**Issue by dippnsk** [jacobdufault/fullserializer#35]
I use custom converter and return fsResult.Fail("message") if I can't serialize an object for some reason.
TrySerialize does not use this result and returns fsResult.Succeeded at the top level. The problem is in the fsResult.AddMessage() call instead of fsResult.Merge() in fsReflectedConverter. But maybe this is intented behaviour? If so, how can I handle failures in custom converters?

**Comment by jacobdufault** [comment]
This is because Full Serializer supports partial deserialization. At the top level, simply check the `fsResult` to see if there are any warning messages. If there are, then the serialization did not go 100% correct, so you know that something failed.

I need to add a `HasWarning` boolean properly to `fsResult`, for but now you can just call `bool hasWarnings = fsResult.RawMessages.Any()` to check if there are warnings (or just call `AssertSuccessWithoutWarnings` if you are fine with exceptions).
